# Generated by Django 2.0.1 on 2018-01-27 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=30)),
                ('book_state', models.IntegerField()),
                ('book_width', models.IntegerField()),
                ('partition_depth', models.IntegerField()),
                ('last_updated', models.DateTimeField()),
                ('colour', models.CharField(blank=True, max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('card_number', models.IntegerField()),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Partition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partition_position', models.CharField(max_length=1)),
                ('partition_space', models.IntegerField()),
                ('shelf_distance', models.IntegerField()),
                ('user_distance', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(0), to='website.Customer'),
        ),
        migrations.AddField(
            model_name='book',
            name='partition',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(0), to='website.Partition'),
        ),
    ]
