# Generated by Django 2.0.1 on 2018-02-05 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=30)),
                ('book_state', models.IntegerField(choices=[(0, 'available'), (1, 'taking'), (2, 'taken'), (3, 'returning'), (4, 'reserved')], default=0)),
                ('book_width', models.IntegerField()),
                ('partition_depth', models.IntegerField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('colour', models.CharField(choices=[('R', 'Red'), ('Y', 'Yellow'), ('G', 'Green'), ('C', 'Cyan'), ('B', 'Blue'), ('M', 'Magenta'), ('W', 'White')], default='R', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('card_number', models.IntegerField()),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Partition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partition_position', models.CharField(max_length=1)),
                ('partition_space', models.IntegerField()),
                ('shelf_distance', models.IntegerField()),
                ('user_distance', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='customer',
            field=models.ForeignKey(default=0, on_delete=models.SET(0), to='website.Customer'),
        ),
        migrations.AddField(
            model_name='book',
            name='partition',
            field=models.ForeignKey(default=0, on_delete=models.SET(0), to='website.Partition'),
        ),
    ]
