# Generated by Django 2.0.1 on 2018-02-05 22:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='last_taken',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
