# Generated by Django 2.0.1 on 2018-02-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_book_last_taken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='partition',
            name='partition_position',
        ),
        migrations.AddField(
            model_name='partition',
            name='section',
            field=models.ForeignKey(default=0, on_delete=models.SET(0), to='website.Section'),
        ),
    ]
