# Generated by Django 2.0.1 on 2018-02-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20180228_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='basket',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
