# Generated by Django 2.0 on 2018-04-17 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20180313_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='picture',
            field=models.CharField(default='', max_length=50),
        ),
    ]
