# Generated by Django 2.0 on 2018-04-18 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_book_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='picture',
            field=models.CharField(default='', max_length=50),
        ),
    ]
